### PR TITLE
chore: update READMEs to Node v12

### PR DESCRIPTION
**Pull request by stvnspchr**
Many students install the latest version of Node v16. And many of our current packages are old enough to not be supported. This update instructs students to install Node v12.

### CODE REVIEW

**Comment by cherimarie** [comment]
I feel like updating packages to work with v16 would be a better approach than pinning 4 versions behind. I believe we updated everything to work with v14 a year ago. If we want to give instructions to use an older version, could we use that instead of 12?

**Comment by cherimarie** [comment]
It looks like v17 is the current: https://nodejs.org/en/about/releases/ 

The class materials last time I saw them specifically gave instructions to install the latest stable version of Node...

**Comment by stvnspchr** [comment]
> It looks like v17 is the current: https://nodejs.org/en/about/releases/
> 
> The class materials last time I saw them specifically gave instructions to install the latest stable version of Node...

If we wanted to update to latest Node, we should stick with even numbers, which are typically LTS. But that problem is many of our npm deps are not supported by 12> (perhaps 14>).

**Comment by stvnspchr** [comment]
> I feel like updating packages to work with v16 would be a better approach than pinning 4 versions behind. I believe we updated everything to work with v14 a year ago. If we want to give instructions to use an older version, could we use that instead of 12?

Ahh okay. I can double check on v14. I know v16 doesn't work for most students. And I do agree on updating packages is the next best step. And something I'm recommending. But in the meantime, I'd like to get students directed towards 12 (or 14).

**Comment by cherimarie** [comment]
#59 supersedes this.

**Pull request closed without merging**
