### PR TITLE
Update gulp & dependencies to support node v16; enforce node version

### PR DESCRIPTION
**Pull request by cherimarie**
@stvnspchr this should work with node v14 and v16. I added enforcement to use version 14 or higher, so if things fail for a student, they'll at least have a clear error message as to why it failed! Could you test this out? If it looks good to you, I'll go through and update all the other directories.

### CODE REVIEW

**Comment by stvnspchr** [comment]
@cherimarie Should we do this for every lesson?

**Comment by stvnspchr** [comment]
> @stvnspchr Yep! If you approve this (after testing locally), I'll do a follow up PR with the same changes to every directory that uses Gulp :)

@cherimarie Tried on both v14 and v16 and it all works perf. And v12 gave a very helpful warning. :D

**Review by stvnspchr — APPROVED** [review]
Looks good!

I think we should hold on merging this, otherwise a student will install Node v14 or greater for this lesson and then run into issues on subsequent lessons.

**Comment by cherimarie** [comment]
@stvnspchr Ok, I updated all the basic lessons 😅  However, the example solution in lesson08 only works with Node v12 and I don't have time today to remember how Vue works and rebuild the solution with a later version of Node. Could you take a swing at that (either on this branch or another)? Then we can merge everything at once. If I find time before you do, I can do it as well.

**Comment by cherimarie** [comment]
@stvnspchr this should be good to go now. I built the lesson 08 solution app with Node v16 and tested it with v12 and v14. I'll let you merge this when you're ready. All changes should work fine with Node v14, and I wouldn't expect students are using any lower version that that, so hopefully there's nothing breaking here.

**Review by kearlyaa — APPROVED** [review]
I was able to run each assignment locally.  Everything looks good.

**Pull request merged**
