### PR TITLE
Assignment2

### PR DESCRIPTION
**Pull request by kurosawaftw7**

### CODE REVIEW

**Comment by kearlyaa** [comment]
The PR request for your assignments should be made against your forked version of the repo, not the original class one.

**Comment by kurosawaftw7** [comment]
Okay, how do I do this correctly? I don't know where to access my forked
version of the repo.

**Comment by kearlyaa** [comment]
When you create the pull request, there will be two drop down menus with
your assignment branch on the right and the main/master on the left.  This
hat left side is where you can change the selection to your repo.

Also be sure you push your changes to your assignment2 branch before
creating the pr.

**Comment by kurosawaftw7** [comment]
https://github.com/kurosawaftw7/html300-v2/pull/1 Okay, is this the correct
one? I committed the latest changes too.

**Pull request closed without merging**
